package com.yemensoft.onyx.classes;


public enum Actions {
    VerifyMobile,
    Login,
    Home,
    ForgotPassword,
    ChangePassword,
    TassdeedBooking,
    SuccesfullyBooking,
    ConfirmeIMEI,
    ConfirmeIMEICode,
    ContactSupport,
    Relogin,
    ReloadHome,
    ReloadData,
    StopService,
    NoData,
    TripSevicStoped,
    WrongData,
    NoSeat,
    WrongAuthriztion,
    Allreadyloggedin,
    Blocked,
    SeatOver,
    NoBlance,
    Success,
    TransactionExepire,
    NoRating,
    NoAutrizedAgnest,
    NotSupported,
    WrongWallet,
    WrongFormatMobile,
    FalidOperation,
    QueryNotSupported,
    QueryOfferNotSupported,
    OfferLess,
    NoPriceFound,
    NoBallance,
    Renew,
    WrongPath,
    Ticket,
    Tassdid
}